---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk:8-jdk
    tag: "latest"


inputs:
  - name: music-repo
  - name: version

run:
  path: music-repo/ci/tasks/build-artifact.sh
