---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8-jdk-alpine"

inputs:
  - name: music-repo
  - name: version
outputs:
  - name: workspace

caches:
  - path: gradle
  #- path: maven

run:
  path: music-repo/ci/tasks/build-artifact.sh
