---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: datianshi/cf-cli
    tag: "latest"

inputs:
  - name: music-repo
  - name: music-release

run:
  path: music-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  HOST:
