---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/artillery-docker
    tag: "latest"

inputs:
- name: music-repo
- name: current-app-info
  optional: true

run:
  path: ./music-repo/ci/tasks/load-tests
